"use client";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
const tips = [
  "Add your classrooms with the + button. They will be displayed below.",
  "Click a class to see its contents on the right, and its settings icon to change the classroom’s content.",
  "Your classroom’s lessons appear here. Add more with the + button.",
  "Download adapted lessons with the Download button. Unzip them and they are ready to use.",
  "Change settings for specific students here. Documents are adapted based on these settings.",
  "See more details of your account here."
];
export default function HomeDashboard() {
  const router = useRouter(); const [classrooms, setClassrooms] = useState([]); const [selected, setSelected] = useState(null); const [lessons, setLessons] = useState([]); const [tour, setTour] = useState(-1); const [user, setUser] = useState(null); const [uploadMessage, setUploadMessage] = useState(""); const fileInput = useRef(null);
  useEffect(() => { Promise.all([fetch("/api/classrooms").then(r => r.json()), fetch("/api/me").then(r => r.json())]).then(([classes, me]) => { setClassrooms(classes.classrooms || []); setUser(me.user); if (classes.classrooms?.length) setSelected(classes.classrooms[0]); }); }, []);
  useEffect(() => { if (!selected) return setLessons([]); fetch(`/api/lessons?classroomId=${selected._id}`).then(r => r.json()).then(r => setLessons(r.lessons || [])); }, [selected]);
  async function upload(event) { const file = event.target.files?.[0]; if (!file || !selected) return; setUploadMessage("Uploading lesson…"); const body = new FormData(); body.append("classroomId", selected._id); body.append("file", file); const response = await fetch("/api/lessons", { method: "POST", body }); const result = await response.json(); setUploadMessage(result.message || result.error || "Unable to upload lesson."); if (response.ok) setLessons(current => [result.lesson, ...current]); event.target.value = ""; }
  return <main className="app-shell"><header className="banner"><h1 className="banner-title">Teacher-Document-Adapter</h1><nav className="banner-actions"><button className="button small-button" onClick={() => setTour(0)}>Help</button><button className="button small-button" onClick={() => router.push("/settings")}>Settings</button><button className="picture-button" title={user ? `${user.username} account` : "Account"} onClick={() => router.push("/profile")}><img src="/icons/account.png" alt="Account" /></button></nav></header><section className="home-grid"><aside className="column"><div className="column-heading"><h2>Classrooms</h2><button className="picture-button" title="Add classroom" onClick={() => router.push("/class")}><img src="/icons/plus.png" alt="Add classroom" /></button></div><ul className="list">{classrooms.map(room => <li className="class-row" key={room._id}><button className="row-main" onClick={() => setSelected(room)}>{room.name}</button><button className="picture-button" title={`Edit ${room.name}`} onClick={() => router.push(`/class?id=${room._id}`)}><img src="/icons/settings.png" alt="Edit classroom" /></button></li>)}</ul>{!classrooms.length && <p className="empty">No classrooms yet. Select + to create one.</p>}</aside><section className="column"><div className="column-heading"><h2>{selected ? selected.name : "Lessons"}</h2>{selected && <><input ref={fileInput} type="file" hidden onChange={upload} accept=".zip,.pdf,.doc,.docx,.ppt,.pptx" /><button className="picture-button" title="Add lesson" onClick={() => fileInput.current?.click()}><img src="/icons/plus.png" alt="Add lesson" /></button></>}</div>{selected ? <><ul className="list">{lessons.map(lesson => <li className="lesson-row" key={lesson._id}><span>{lesson.name} {lesson.status !== "ready" && `(${lesson.status.replaceAll("_", " ")})`}</span><button className="button row-action" disabled={lesson.status !== "ready"} onClick={() => window.location.assign(`/api/lessons/${lesson._id}/download`)}>Download</button></li>)}{!lessons.length && <p className="empty">No lessons have been added to this classroom.</p>}</ul><p className={uploadMessage.includes("Unable") ? "message" : "success"}>{uploadMessage}</p></> : <p className="empty">Select a classroom to see its lessons.</p>}</section></section>{tour >= 0 && <div className="tour" onClick={() => setTour(tour === tips.length - 1 ? -1 : tour + 1)}><div className="tour-card"><p className="tour-count">{tour + 1} / {tips.length}</p><p>{tips[tour]}</p><button className="button">{tour === tips.length - 1 ? "Finish" : "Next"}</button></div></div>}</main>;
}
